export const data = [
  {
    trainingCode: "REACT301",
    trainingName: "React XT  401",
    startDate: "2022-09-01",
    phase: "",
    type: "Instructor led",
    endDate: "2022-09-20",
    status: "In Progress",
    PPC_OracleID: "pawankum",
    PPC_FirstName: "Pawan",
    PPC_LastName: "Kumar",
    PPC_Email: "pawan.kumar@publicissapient.com",
    SPC_oracleID: "arindamdat",
    SPC_FirstName: "Arindam",
    SPC_LastName: "Dutta",
    SPC_Email: "arindam.dutta@publicissapient.com",
    oracleID: "pawankum ,arindamdat ",
    docs: [],
    id: "594ca5e4-5613-46e1-a80e-931b26e58945",
  },
];

export const mockuser = {
  trainingCode: "REACT301",
  trainingName: "React XT  401",
  startDate: "2022-09-01",
  phase: "",
  type: "Instructor led",
  endDate: "2022-09-20",
  status: "In Progress",
  PPC_OracleID: "pawankum",
  PPC_FirstName: "Pawan",
  PPC_LastName: "Kumar",
  PPC_Email: "pawan.kumar@publicissapient.com",
  SPC_oracleID: "arindamdat",
  SPC_FirstName: "Arindam",
  SPC_LastName: "Dutta",
  SPC_Email: "arindam.dutta@publicissapient.com",
  oracleID: "pawankum ,arindamdat ",
  docs: [],
  id: "594ca5e4-5613-46e1-a80e-931b26e58945",
};
